import { cn } from "@/lib/utils";
import { AlertTriangle, MapPin, Clock, Shield, CheckCircle2, Eye, CircleCheck, Heart, ChevronDown, ChevronUp, HelpCircle, Radio, Phone, Satellite, Users, Info } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { useState } from "react";
import type { AlertStatus, UserRole } from "@/contexts/DemoModeContext";

export type SourceType = "911_call" | "citizen_report" | "sensor" | "community_tip" | "system";

const SOURCE_CONFIG: Record<SourceType, { icon: typeof Phone; label: string; color: string; description: string }> = {
  "911_call": { icon: Phone, label: "911 Call", color: "text-danger", description: "Received via emergency dispatch system" },
  "citizen_report": { icon: Users, label: "Citizen Report", color: "text-mrsg-cyan", description: "Submitted through the citizen portal" },
  "sensor": { icon: Satellite, label: "Sensor Alert", color: "text-escalating", description: "Detected by automated monitoring system" },
  "community_tip": { icon: Radio, label: "Community Tip", color: "text-stable", description: "Anonymous tip from community member" },
  "system": { icon: Info, label: "System", color: "text-muted-foreground", description: "Generated by LPM system analysis" },
};

function formatRelativeTime(timestamp: string): { text: string; urgency: "recent" | "moderate" | "stale" } {
  const now = new Date();
  
  // Handle HH:MM:SS format (common in demo data)
  const timeOnlyMatch = timestamp.match(/^(\d{1,2}):(\d{2}):(\d{2})$/);
  if (timeOnlyMatch) {
    const [, hours, minutes, seconds] = timeOnlyMatch;
    const today = new Date();
    today.setHours(parseInt(hours, 10), parseInt(minutes, 10), parseInt(seconds, 10), 0);
    
    const diffMs = now.getTime() - today.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    
    if (diffMins < 0) {
      // Timestamp is in the future (likely from yesterday's context)
      return { text: "Recent", urgency: "recent" };
    } else if (diffMins < 5) {
      return { text: "Just now", urgency: "recent" };
    } else if (diffMins < 60) {
      return { text: `${diffMins}m ago`, urgency: "recent" };
    } else {
      const diffHours = Math.floor(diffMins / 60);
      if (diffHours < 2) {
        return { text: `${diffHours}h ago`, urgency: "moderate" };
      }
      return { text: `${diffHours}h ago`, urgency: "stale" };
    }
  }
  
  // Handle full date/time formats
  const date = new Date(timestamp);
  if (isNaN(date.getTime())) {
    // Fallback for unparseable timestamps
    return { text: timestamp, urgency: "recent" };
  }
  
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMins < 5) {
    return { text: "Just now", urgency: "recent" };
  } else if (diffMins < 60) {
    return { text: `${diffMins}m ago`, urgency: "recent" };
  } else if (diffHours < 2) {
    return { text: `${diffHours}h ago`, urgency: "moderate" };
  } else if (diffHours < 24) {
    return { text: `${diffHours}h ago`, urgency: "stale" };
  } else {
    return { text: `${diffDays}d ago`, urgency: "stale" };
  }
}

const URGENCY_COLORS = {
  recent: "text-danger",
  moderate: "text-escalating",
  stale: "text-muted-foreground",
};

const GUIDANCE_BY_STATUS: Record<AlertStatus, { title: string; tips: string[] }> = {
  active: {
    title: "Immediate Response Guidance",
    tips: [
      "Verify caller safety and location accuracy",
      "Assess scene dynamics before dispatching",
      "Consider trauma-informed communication approach",
      "Prepare backup resources if escalation likely",
    ],
  },
  acknowledged: {
    title: "Coordination Guidance",
    tips: [
      "Maintain calm, clear communication with responder",
      "Monitor for status changes or escalation",
      "Document all timeline events accurately",
      "Prepare secondary resources if needed",
    ],
  },
  monitoring: {
    title: "Monitoring Guidance",
    tips: [
      "Check in with responder at regular intervals",
      "Watch for signs of situation de-escalation",
      "Prepare follow-up support resources",
      "Document resolution pathway",
    ],
  },
  resolved: {
    title: "Post-Incident Guidance",
    tips: [
      "Ensure all parties have support resources",
      "Complete documentation while details are fresh",
      "Note any lessons for future response",
      "Acknowledge team effort in resolution",
    ],
  },
};

interface IncidentCardProps {
  id: string;
  title: string;
  location: string;
  timestamp: string;
  assignedResponder?: string;
  isPinned?: boolean;
  className?: string;
  status?: AlertStatus;
  acknowledgedBy?: string;
  acknowledgedAt?: string;
  resolvedBy?: string;
  resolvedAt?: string;
  userRole?: UserRole;
  onStatusChange?: (newStatus: AlertStatus) => void;
  canTransition?: (newStatus: AlertStatus) => boolean;
  sourceType?: SourceType;
  zone?: string;
  whyShowing?: string;
}

const STATUS_CONFIG: Record<AlertStatus, { label: string; color: string; bgColor: string }> = {
  active: { label: "Active", color: "text-danger", bgColor: "bg-danger/20" },
  acknowledged: { label: "Acknowledged", color: "text-escalating", bgColor: "bg-escalating/20" },
  monitoring: { label: "Monitoring", color: "text-mrsg-cyan", bgColor: "bg-mrsg-cyan/20" },
  resolved: { label: "Resolved", color: "text-stable", bgColor: "bg-stable/20" },
};

export function IncidentCard({
  id,
  title,
  location,
  timestamp,
  assignedResponder,
  isPinned,
  className,
  status = "active",
  acknowledgedBy,
  acknowledgedAt,
  resolvedBy,
  resolvedAt,
  userRole,
  onStatusChange,
  canTransition,
  sourceType = "911_call",
  zone,
  whyShowing,
}: IncidentCardProps) {
  const [showGuidance, setShowGuidance] = useState(false);
  const [showWhyInfo, setShowWhyInfo] = useState(false);
  const statusConfig = STATUS_CONFIG[status];
  const isActive = status === "active";
  const isResolved = status === "resolved";
  const guidance = GUIDANCE_BY_STATUS[status];
  const sourceConfig = SOURCE_CONFIG[sourceType];
  const SourceIcon = sourceConfig.icon;
  const relativeTime = formatRelativeTime(timestamp);
  
  const defaultWhyShowing = whyShowing || `This alert appears in your feed because it is within your assigned ${zone ? `zone (${zone})` : "coverage area"} and matches your role permissions. Source: ${sourceConfig.label}.`;

  return (
    <div
      className={cn(
        "rounded-lg border-2 p-4 transition-all duration-300",
        isPinned && isActive
          ? "border-danger bg-danger/5 shadow-lg shadow-danger/10"
          : status === "acknowledged"
          ? "border-escalating/50 bg-escalating/5"
          : status === "monitoring"
          ? "border-mrsg-cyan/50 bg-mrsg-cyan/5"
          : status === "resolved"
          ? "border-stable/50 bg-stable/5"
          : "border-card-border bg-card/60",
        className
      )}
      data-testid={`incident-card-${id}`}
    >
      <div className="flex items-start justify-between gap-2 mb-3">
        <div className="flex items-center gap-2">
          <div className={cn(
            "flex items-center justify-center h-6 w-6 rounded-full",
            statusConfig.bgColor
          )}>
            {isResolved ? (
              <CircleCheck className={cn("h-3 w-3", statusConfig.color)} />
            ) : status === "monitoring" ? (
              <Eye className={cn("h-3 w-3", statusConfig.color)} />
            ) : status === "acknowledged" ? (
              <CheckCircle2 className={cn("h-3 w-3", statusConfig.color)} />
            ) : (
              <AlertTriangle className={cn("h-3 w-3", statusConfig.color)} />
            )}
          </div>
          <Badge variant="outline" className={cn("text-[10px] uppercase tracking-wider", statusConfig.color)}>
            {statusConfig.label}
          </Badge>
        </div>
        <span className="text-xs font-mono text-muted-foreground">
          {id}
        </span>
      </div>

      <h3 className="text-sm font-medium text-foreground mb-3">
        {title}
      </h3>

      <div className="flex flex-col gap-2 text-xs">
        <div className="flex items-center gap-2 text-muted-foreground">
          <MapPin className="h-3 w-3" />
          <span>{location}</span>
        </div>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Clock className="h-3 w-3 text-muted-foreground" />
            <span className={cn("font-medium", URGENCY_COLORS[relativeTime.urgency])}>
              {relativeTime.text}
            </span>
            <span className="text-muted-foreground">({timestamp})</span>
          </div>
          <Tooltip>
            <TooltipTrigger asChild>
              <div className={cn("flex items-center gap-1.5 px-2 py-0.5 rounded-full", sourceConfig.color, "bg-muted/30")}>
                <SourceIcon className="h-3 w-3" />
                <span className="text-[10px] font-medium">{sourceConfig.label}</span>
              </div>
            </TooltipTrigger>
            <TooltipContent side="top" className="max-w-[200px]">
              <p className="text-xs">{sourceConfig.description}</p>
            </TooltipContent>
          </Tooltip>
        </div>
        {assignedResponder && (
          <div className="flex items-center gap-2 text-mrsg-cyan">
            <Shield className="h-3 w-3" />
            <span>{assignedResponder}</span>
          </div>
        )}
        {acknowledgedBy && acknowledgedAt && (
          <div className="flex items-center gap-2 text-escalating">
            <CheckCircle2 className="h-3 w-3" />
            <span>Acknowledged by {acknowledgedBy} at {acknowledgedAt}</span>
          </div>
        )}
        {resolvedBy && resolvedAt && (
          <div className="flex items-center gap-2 text-stable">
            <CircleCheck className="h-3 w-3" />
            <span>Resolved by {resolvedBy} at {resolvedAt}</span>
          </div>
        )}
      </div>

      {onStatusChange && userRole && !isResolved && (
        <div className="mt-4 flex flex-wrap gap-2">
          {status === "active" && userRole === "dispatcher" && canTransition?.("acknowledged") && (
            <Button
              size="sm"
              variant="outline"
              className="text-escalating border-escalating/50"
              onClick={() => onStatusChange("acknowledged")}
              data-testid={`button-acknowledge-${id}`}
            >
              <CheckCircle2 className="h-3 w-3 mr-1" />
              Acknowledge
            </Button>
          )}
          {status === "acknowledged" && canTransition?.("monitoring") && (
            <Button
              size="sm"
              variant="outline"
              className="text-mrsg-cyan border-mrsg-cyan/50"
              onClick={() => onStatusChange("monitoring")}
              data-testid={`button-monitor-${id}`}
            >
              <Eye className="h-3 w-3 mr-1" />
              Set Monitoring
            </Button>
          )}
          {(status === "acknowledged" || status === "monitoring") && 
           (userRole === "responder" || userRole === "citizen") && 
           canTransition?.("resolved") && (
            <Button
              size="sm"
              variant="outline"
              className="text-stable border-stable/50"
              onClick={() => onStatusChange("resolved")}
              data-testid={`button-resolve-${id}`}
            >
              <CircleCheck className="h-3 w-3 mr-1" />
              Resolve
            </Button>
          )}
        </div>
      )}

      <div className="mt-4 pt-3 border-t border-border/50">
        <button
          className="flex items-center gap-2 text-xs text-muted-foreground w-full"
          onClick={() => setShowGuidance(!showGuidance)}
          data-testid={`button-toggle-guidance-${id}`}
        >
          <Heart className="h-3 w-3 text-stable" />
          <span className="font-medium">{guidance.title}</span>
          {showGuidance ? (
            <ChevronUp className="h-3 w-3 ml-auto" />
          ) : (
            <ChevronDown className="h-3 w-3 ml-auto" />
          )}
        </button>
        {showGuidance && (
          <ul className="mt-2 space-y-1.5 text-xs text-muted-foreground pl-5" data-testid={`guidance-list-${id}`}>
            {guidance.tips.map((tip, i) => (
              <li key={i} className="flex items-start gap-2">
                <span className="text-stable shrink-0">{i + 1}.</span>
                <span>{tip}</span>
              </li>
            ))}
          </ul>
        )}
      </div>

      <div className="mt-3 pt-3 border-t border-border/50">
        <button
          className="flex items-center gap-2 text-xs text-muted-foreground w-full"
          onClick={() => setShowWhyInfo(!showWhyInfo)}
          data-testid={`button-toggle-why-${id}`}
        >
          <HelpCircle className="h-3 w-3 text-mrsg-cyan" />
          <span className="font-medium">Why am I seeing this?</span>
          {showWhyInfo ? (
            <ChevronUp className="h-3 w-3 ml-auto" />
          ) : (
            <ChevronDown className="h-3 w-3 ml-auto" />
          )}
        </button>
        {showWhyInfo && (
          <div className="mt-2 p-3 rounded-md bg-muted/30 text-xs text-muted-foreground" data-testid={`why-info-${id}`}>
            <p>{defaultWhyShowing}</p>
            <div className="mt-2 flex flex-wrap gap-2">
              {zone && (
                <Badge variant="outline" className="text-[10px] text-mrsg-cyan">
                  Zone: {zone}
                </Badge>
              )}
              <Badge variant="outline" className="text-[10px]">
                <SourceIcon className="h-2.5 w-2.5 mr-1" />
                {sourceConfig.label}
              </Badge>
              <Badge variant="outline" className={cn("text-[10px]", URGENCY_COLORS[relativeTime.urgency])}>
                {relativeTime.text}
              </Badge>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
